---
- name: "Begin {{ role_name }}/custom/pre_tasks.yml"
  debug:
    msg: "Begin {{ role_name }}/custom/pre_tasks.yml"

- name: Update apt cache
  ansible.builtin.package:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install PostgreSQL and related packages
  ansible.builtin.package:
    name:
      - postgresql-common
      - python3-psycopg2
      - libpq-dev
      - curl
      - ufw
      - gnupg2
      - wget
      - lsb-release
      - ca-certificates
      - pgbackrest
      - pgloader
      - postgresql-server-dev-{{ postgresql_version }}
      - postgresql-client-{{ postgresql_version }}
      - postgresql-{{ postgresql_version }}
      - postgresql-contrib-{{ postgresql_version }}
    state: present
  # when: ansible_os_family == "Debian"

- name: "End {{ role_name }}/custom/pre_tasks.yml"
  debug:
    msg: "End {{ role_name }}/custom/pre_tasks.yml"