---
- name: "Begin {{ role_name }}/tasks/custom/postgres_installation.yml"
  debug:
    msg: "Begin {{ role_name }}/tasks/custom/postgres_installation.yml"

# - name: Add PostgreSQL apt key
#   apt_key:
#     url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
#     state: present

# - name: Add PostgreSQL repository
#   apt_repository:
#     repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
#     state: present

- name: Ensure PostgreSQL service is started and enabled
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Check PostgreSQL status
  command: systemctl status postgresql
  register: pg_status
  changed_when: false
  ignore_errors: yes

- name: Show PostgreSQL status
  debug:
    var: pg_status.stdout_lines

- name: "End {{ role_name }}/tasks/custom/postgres_installation.yml"
  debug:
    msg: "End {{ role_name }}/tasks/custom/postgres_installation.yml"