---
- name: "Begin {{ role_name }}/main.yml"
  debug:
    msg: "Begin {{ role_name }}/main.yml"

- name: Include custom/packages.yml
  include_tasks: custom/packages.yml

- name: Include custom/postgres_installation.yml
  include_tasks: custom/postgres_installation.yml

- name: Include custom/postgres_configuration.yml
  include_tasks: custom/postgres_configuration.yml

- name: "End {{ role_name }}/main.yml"
  debug:
    msg: "End {{ role_name }}/main.yml"